### ISSUE TITLE
您好，文章中的方法没有使用template和verbalizer，请问模型和提示学习有何关系？并且ablation study没有研究不在数据集上预训练直接使用LPD这种情况,请问模型最终work的原因到底是LPD还是预训练在起作用？

### ISSUE THREAD

**Issue by qq31415926** [jzhang38/LPD#1]
如题。

**Comment by jzhang38** [comment]
您好，
谢谢您对我们工作的关注。

1. 我们直接将textual label和context sentence用冒号连在一起， 我们认为textual label起到了“提示”的作用， 从而让模型能够从context sentence中extract出better representation.  我们有明确指出我们的“prompt”有别于PET那种prompt。 从另外一个角度来说， 你可以认为我们的template是 [textual label]:[context sentence]. 另外， 其实不是所有的prompt learning都要有verbalizer,  比如CoT就没有verbalizer.
2. Table 3 有没有预训练的情况。

Hope that clarifies. 

Hi，
Thanks for your attention on our work.

1. We directly connect the textual label and the context sentence with a colon. We think that the textual label acts as a "prompt", so that the model can extract a better representation from the context sentence. We have clearly pointed out our "prompt" is different from the PET style prompt. From another point of view, you can think that our template is "[textual label]:[context sentence]". In addition, not all prompt-based learning needs to have a verbalizer, for example, CoT does not have a verbalizer.
2. Table 3 (top part) has included the case where LPD did not go through pre-training.

Hope that clarifies.

**Comment by jzhang38** [comment]
I will close this thread since there is no futher discussion.
